# Generated by Django 3.0.5 on 2020-04-28 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200428_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 13, 57, 43, 883248, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
