# Generated by Django 3.0.5 on 2020-04-28 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200428_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 13, 59, 41, 926966, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
